name: Continuous Integration

on: 
  push:
    -master
    -develop
  pull_request:
    -master
    -develop

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm build

      - name: Test
        run: npm test --watchAll=false